package com.harthoric.caesim.entity.type;

public enum Type {

	// government
	AGENT, OFFICER, POLITICIAN, MEDIC, LAWYER, BANKER, UNDERSCOVER, SCIENTIST, ENGINEER, GARBAGE,

	// wealthy
	BUSINESS, RICHIE, RETIRED, ZOMBIE, ROGUE,

	// leftovers
	KINGPIN, MINION, WORKER, SCAVENGER, SMUGGLER, VAGRANT, OUTCAST,

	// hacker
	BLACK_HAT, GREY_HAT, WHITE_HAT,

	// important
	FORGOTTEN_WANDERER, THE_MARK, SMOKE, THE_ROGUE,

	// animals
	// - birds
	PIGEON, HAWK, GULL, ROBIN, BLACKBIRD, STARLING, FINCH, WHITE_DOVE, WOOD_PECKER, OWL, TIT, SPARROW, MAGPIE, CROW,
	JAY, WREN, EAGLE, CRANE, FALCON, NIGHTINGALE, PEACOCK,
	// - dogs
	BLACK_WOLF, GREY_WOLF, WHITE_WOLF, STRAY_DOG, DOG,
	// - cats
	BLACK_CAT, GREY_CAT, WHITE_CAT, STRAY_CAT, CAT,
	// - rodents
	RAT, MOUSE, SQUIRREL, MOLE,

}
